### ISSUE TITLE
[Chore] Initialize and setup Project

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/shorten-link-mac#1]
## Why

- Set up the project with UIKit
- Create project from [ios-template](https://github.com/nimblehq/ios-templates) is preferred
 
## Who Benefits?

- Developers can work on their tasks

**Comment by blyscuit** [comment]
@vnntsu  Will we be working with MacCatalyst? Please note that UIKit is only for iOS and Catalyst while AppKit is for MacOS https://stackoverflow.com/questions/51517510/what-is-the-difference-between-appkit-and-uikit.

The extension (menu bar) will need to be done in AppKit while the main application can be either Catalyst(UIKit or SwiftUI) or AppKit.

**Comment by blyscuit** [comment]
I also suggest we should focus on the menu application since most of us will have to learn AppKit and it seems to be the most useful part of the app. This could take a longer time than we expected.
 However, this depends on your decision, to work on both the main and extension app or work on one part of the app first.

**Comment by blyscuit** [comment]
Luckily there's a way to embed SwiftUI inside AppKit 🎉 https://medium.com/@acwrightdesign/creating-a-macos-menu-bar-application-using-swiftui-54572a5d5f87
I could not find the equivalent for embed UIKit inside AppKit tho.

**Comment by blyscuit** [comment]
Fell free to close this. @phongvhd93
